# Generated by Django 3.0.4 on 2020-03-27 23:19

import analyst.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('kind', models.CharField(choices=[('I', 'Indice'), ('S', 'Stock'), ('F', 'Forex'), ('C', 'Crypto-currency')], max_length=1, null=True)),
                ('ticker', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=60, null=True)),
                ('link', models.CharField(max_length=64, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('indices', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('weights', django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True)),
                ('assets', models.ManyToManyField(to='analyst.Asset')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, analyst.models.DataFrameManager),
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('link', models.CharField(max_length=64, null=True)),
                ('country', models.CharField(max_length=64, null=True)),
                ('assets', models.ManyToManyField(to='analyst.Asset')),
                ('indice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='indice', to='analyst.Asset')),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, analyst.models.DataFrameManager),
        ),
    ]
